### PR TITLE
Update to latest version (1.8.7)

### PR DESCRIPTION
**Pull request by amontalban**
Hi @corux,

I'm updating this formula to latest version but I would love to have this under saltstack-formulas roof.

Maybe @gravyboat can help with that?

Thanks!

### CODE REVIEW

**Comment by gravyboat** [comment]
Here you go: https://github.com/saltstack-formulas/vagrant-formula

**Comment by corux** [comment]
@gravyboat I would prefer to transfer this formula to the saltstack-formulas group. Is this ok with you? The existing repo (https://github.com/saltstack-formulas/vagrant-formula) should be deleted then.

**Comment by corux** [comment]
@amontalban Thanks a lot for the update!

**Comment by gravyboat** [comment]
@corux Yeah that's fine by me, I'll delete it. Let me know if you need anything else, I haven't done a repo transfer in a long time.

Edit: Deleted.

**Pull request merged**
